apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform-managed apps for local cluster
  sourceRepos:
    - https://github.com/amrutp24/gitops-kind.git
  destinations:
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: whoami
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "networking.k8s.io"
      kind: IngressClass
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
