apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amrutp24/gitops-kind.git
    targetRevision: main
    path: clusters/local
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
